module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        'primary-0': "var(--primary-0)",
        'primary-50': "var(--primary-50)",
        'primary-100': "var(--primary-100)",
        'primary-200': "var(--primary-200)",
        'primary-300': "var(--primary-300)",
        'primary-400': "var(--primary-400)",
        'primary-500': "var(--primary-500)",
        'primary-600': "var(--primary-600)",
        'primary-700': "var(--primary-700)",
        'primary-800': "var(--primary-800)",
        'primary-900': "var(--primary-900)",
        'primary-1000': "var(--primary-1000)",
        'primary-1100': "var(--primary-1100)",
        'red-light': "var(--red-light)",
        'red-dark': "var(--red-dark)",
        'green-light': "var(--green-light)",
        'green-dark': "var(--green-dark)",
        'shadow-1': "var(--shadow-1)",
        'shadow-2': "var(--shadow-2)",
        'shadow-3': "var(--shadow-3)",
        'shadow-4': "var(--shadow-4)",
        'defaultFontSize': "var(--defaultFontSize)",
        'headingFont': "var(--headingFont)",
        'bodyFont': "var(--bodyFont)",
        'smallText': "var(--smallText)",
        'extraSmallText': "var(--extraSmallText)",
        'backgroundColor': "var(--backgroundColor)",
        'textColor': "var(--textColor)",
        'borderRadius': "var(--borderRadius)",
        'letterSpacing': "var(--letterSpacing)",
        'transition': "var(--transition)",
        'max-width': "var(--max-width)",
        'fixed-width': "var(--fixed-width)",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
